# Generated by Django 5.0 on 2024-03-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_donation_delete_cryptoaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
